#!/bin/sh
set -x
set -e

PACKAGE="gites-intranet"
PACKAGE_HOME="/home/gdw/$PACKAGE"

case "$1" in
    configure)
	# create var
	/bin/chown -R gdw.gdw $PACKAGE_HOME
	/etc/init.d/gites-intranet-instance02 restart
    ;;

    abort-remove|abort-upgrade|abort-deconfigure)
        echo "abort"
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
